### ISSUE TITLE
Exclude index.html from published NPM package

### ISSUE THREAD

**Issue by melkorCBA** [ryanve/eol#38]
This issue stems from the presence of `index.html` within the project, which serves as an example. This file includes a vulnerable version of `jQuery (jquery@3.1.1)`. Considering that this HTML file is merely an example and is not intended for direct usage within projects, its inclusion tends to pop up in vulnerability scanners like MEND (which is the case for me).

**Proposed Solution:**
excluding index.html from the npm package by adding it to the .npmignore file.

**Comment by ryanve** [comment]
thanks the page no longer uses jQuery since #39 
keeping `index.html` in the package for sure
[it's the project homepage and includes documentation](https://ryanve.dev/eol/)
